-- MySQL Script generated by MySQL Workbench
-- Thu Jul 17 14:37:09 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema HealthGo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HealthGo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HealthGo` DEFAULT CHARACTER SET utf8 ;
USE `HealthGo` ;

-- -----------------------------------------------------
-- Table `HealthGo`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`Estado` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(255) NOT NULL,
  `Sigla` CHAR(4) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`Cidade` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(255) NOT NULL,
  `Estado_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Cidade_Estado1_idx` (`Estado_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Cidade_Estado1`
    FOREIGN KEY (`Estado_Id`)
    REFERENCES `HealthGo`.`Estado` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`Pessoa` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `DataNascimento` DATE NOT NULL,
  `CPF` VARCHAR(14) NOT NULL,
  `Telefone` VARCHAR(45) NULL,
  `Email` VARCHAR(255) NOT NULL,
  `Senha` VARCHAR(255) NOT NULL,
  `EnderecoFoto` VARCHAR(255) NULL,
  `CaoGuia` TINYINT(1) NULL DEFAULT 0,
  `CEP` VARCHAR(20) NOT NULL,
  `Bairro` VARCHAR(255) NOT NULL,
  `Rua` VARCHAR(255) NOT NULL,
  `NumeroEndereco` VARCHAR(255) NOT NULL,
  `Cidade_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Pessoa_Cidade1_idx` (`Cidade_Id` ASC) VISIBLE,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoa_Cidade1`
    FOREIGN KEY (`Cidade_Id`)
    REFERENCES `HealthGo`.`Cidade` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`ContaGerencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`ContaGerencia` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(255) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `Senha` VARCHAR(255) NOT NULL,
  `CNPJ` VARCHAR(18) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`Hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`Hotel` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `CNPJ` VARCHAR(18) NOT NULL,
  `Nome` VARCHAR(255) NOT NULL,
  `Tipo` ENUM('Casa', 'Apartamento', 'Hostel', 'Pousada', 'Hotel') NOT NULL,
  `Email` VARCHAR(150) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  `Site` VARCHAR(255) NULL,
  `Acessibilidade` VARCHAR(255) NULL,
  `CEP` VARCHAR(20) NOT NULL,
  `Bairro` VARCHAR(255) NOT NULL,
  `Rua` VARCHAR(255) NOT NULL,
  `NumeroEndereco` VARCHAR(255) NOT NULL,
  `Descricao` VARCHAR(255) NULL,
  `Ativo` TINYINT(1) NULL DEFAULT 1,
  `DataInicio` DATETIME NULL,
  `Cidade_Id` INT NOT NULL,
  `ContaGerencia_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Hotel_Cidade1_idx` (`Cidade_Id` ASC) VISIBLE,
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  INDEX `fk_Hotel_ContaGerencia1_idx` (`ContaGerencia_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Hotel_Cidade1`
    FOREIGN KEY (`Cidade_Id`)
    REFERENCES `HealthGo`.`Cidade` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hotel_ContaGerencia1`
    FOREIGN KEY (`ContaGerencia_Id`)
    REFERENCES `HealthGo`.`ContaGerencia` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`Lembrete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`Lembrete` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NOT NULL,
  `Data` DATETIME NOT NULL,
  `Tipo` ENUM('Remédio', 'Consulta', 'Outro') NOT NULL,
  `Pessoa_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Lembrete_Pessoa1_idx` (`Pessoa_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Lembrete_Pessoa1`
    FOREIGN KEY (`Pessoa_Id`)
    REFERENCES `HealthGo`.`Pessoa` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`Quarto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`Quarto` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Numero` VARCHAR(25) NOT NULL,
  `Andar` INT NULL,
  `AceitaAnimal` TINYINT(1) NOT NULL,
  `Observacao` VARCHAR(255) NULL,
  `Preco` DECIMAL(10,2) NOT NULL,
  `LimitePessoa` INT NOT NULL,
  `Hotel_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Quarto_Hotel1_idx` (`Hotel_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Quarto_Hotel1`
    FOREIGN KEY (`Hotel_Id`)
    REFERENCES `HealthGo`.`Hotel` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`OrdemServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`OrdemServico` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `DataCriacao` DATETIME NOT NULL,
  `StatusOS` ENUM('Concluído', 'Em andamento', 'Cancelado') NULL,
  `FormaPagamento` VARCHAR(55) NULL,
  `Pessoa_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_OrdemServico_Pessoa1_idx` (`Pessoa_Id` ASC) VISIBLE,
  CONSTRAINT `fk_OrdemServico_Pessoa1`
    FOREIGN KEY (`Pessoa_Id`)
    REFERENCES `HealthGo`.`Pessoa` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`OrdemServico_Hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`OrdemServico_Hotel` (
  `StatusOS` ENUM('Concluído', 'Em andamento', 'Cancelado') NULL,
  `Preco` DECIMAL(10,2) NULL,
  `Observacao` VARCHAR(255) NULL,
  `QuantAcompanhante` INT NOT NULL,
  `DataInicio` DATETIME NOT NULL,
  `DataFim` DATETIME NOT NULL,
  `Quarto_Id` INT NOT NULL,
  `OrdemServico_Id` INT NOT NULL,
  INDEX `fk_OrdemServico_Quarto1_idx` (`Quarto_Id` ASC) VISIBLE,
  INDEX `fk_OrdemServico_Hotel_OrdemServico1_idx` (`OrdemServico_Id` ASC) VISIBLE,
  CONSTRAINT `fk_OrdemServico_Quarto1`
    FOREIGN KEY (`Quarto_Id`)
    REFERENCES `HealthGo`.`Quarto` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrdemServico_Hotel_OrdemServico1`
    FOREIGN KEY (`OrdemServico_Id`)
    REFERENCES `HealthGo`.`OrdemServico` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`PrestadorServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`PrestadorServico` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Observacao` VARCHAR(255) NULL,
  `CNPJ` VARCHAR(45) NULL,
  `Ativo` TINYINT(1) NULL DEFAULT 1,
  `Pessoa_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_PrestadorServico_has_Especialidade_Pessoa1_idx` (`Pessoa_Id` ASC) VISIBLE,
  CONSTRAINT `fk_PrestadorServico_has_Especialidade_Pessoa1`
    FOREIGN KEY (`Pessoa_Id`)
    REFERENCES `HealthGo`.`Pessoa` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`Especialidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`Especialidade` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`PrestadorServico_Especialidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`PrestadorServico_Especialidade` (
  `PrestadorServico_Id` INT NOT NULL,
  `Especialidade_Id` INT NOT NULL,
  `PrecoHora` DECIMAL(10,2) NULL,
  PRIMARY KEY (`PrestadorServico_Id`, `Especialidade_Id`),
  INDEX `fk_PrestadorServico_has_Especialidade_Especialidade1_idx` (`Especialidade_Id` ASC) VISIBLE,
  INDEX `fk_PrestadorServico_has_Especialidade_PrestadorServico1_idx` (`PrestadorServico_Id` ASC) VISIBLE,
  CONSTRAINT `fk_PrestadorServico_has_Especialidade_PrestadorServico1`
    FOREIGN KEY (`PrestadorServico_Id`)
    REFERENCES `HealthGo`.`PrestadorServico` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PrestadorServico_has_Especialidade_Especialidade1`
    FOREIGN KEY (`Especialidade_Id`)
    REFERENCES `HealthGo`.`Especialidade` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`OrdemServico_PrestadorServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`OrdemServico_PrestadorServico` (
  `Preco` DECIMAL(10,2) NOT NULL,
  `HorasTrabalhadas` INT NOT NULL,
  `DataInicio` DATETIME NOT NULL,
  `DataFim` DATETIME NOT NULL,
  `StatusOS` ENUM('Concluído', 'Em andamento', 'Cancelado') NULL,
  `OrdemServico_Id` INT NOT NULL,
  `PrestadorServico_Especialidade_PrestadorServico_Id` INT NOT NULL,
  `PrestadorServico_Especialidade_Especialidade_Id` INT NOT NULL,
  INDEX `fk_OrdemServico_PrestadorServico_OrdemServico1_idx` (`OrdemServico_Id` ASC) VISIBLE,
  INDEX `fk_OrdemServico_PrestadorServico_PrestadorServico_Especiali_idx` (`PrestadorServico_Especialidade_PrestadorServico_Id` ASC, `PrestadorServico_Especialidade_Especialidade_Id` ASC) VISIBLE,
  CONSTRAINT `fk_OrdemServico_PrestadorServico_OrdemServico1`
    FOREIGN KEY (`OrdemServico_Id`)
    REFERENCES `HealthGo`.`OrdemServico` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrdemServico_PrestadorServico_PrestadorServico_Especialida1`
    FOREIGN KEY (`PrestadorServico_Especialidade_PrestadorServico_Id` , `PrestadorServico_Especialidade_Especialidade_Id`)
    REFERENCES `HealthGo`.`PrestadorServico_Especialidade` (`PrestadorServico_Id` , `Especialidade_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`CamaQuarto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`CamaQuarto` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Quantidade` INT NOT NULL,
  `TipoCama` ENUM('Solteiro', 'Casal', 'Beliche', 'Futon') NOT NULL,
  `Quarto_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Cama_has_Quarto_Quarto1_idx` (`Quarto_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Cama_has_Quarto_Quarto1`
    FOREIGN KEY (`Quarto_Id`)
    REFERENCES `HealthGo`.`Quarto` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`Aeroporto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`Aeroporto` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(255) NOT NULL,
  `CodigoIata` CHAR(3) NOT NULL,
  `Cidade_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `CodigoIata_UNIQUE` (`CodigoIata` ASC) VISIBLE,
  INDEX `fk_Aeroporto_Cidade1_idx` (`Cidade_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Aeroporto_Cidade1`
    FOREIGN KEY (`Cidade_Id`)
    REFERENCES `HealthGo`.`Cidade` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`Aviao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`Aviao` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `QuantidadeVaga` INT NOT NULL,
  `CodigoRegistro` VARCHAR(255) NOT NULL,
  `Companhia` VARCHAR(45) NOT NULL,
  `Modelo` VARCHAR(100) NOT NULL,
  `Fabricante` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `CodigoRegistro_UNIQUE` (`CodigoRegistro` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`Assento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`Assento` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Numero` VARCHAR(10) NOT NULL,
  `Tipo` ENUM('Economico', 'Executivo', 'Primeira Classe') NOT NULL,
  `Preco` DOUBLE(10,2) NOT NULL,
  `Aviao_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Assento_Aviao1_idx` (`Aviao_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Assento_Aviao1`
    FOREIGN KEY (`Aviao_Id`)
    REFERENCES `HealthGo`.`Aviao` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`Voo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`Voo` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `CodigoVoo` VARCHAR(10) NOT NULL,
  `DataHoraPartida` DATETIME NOT NULL,
  `DataHoraChegada` DATETIME NOT NULL,
  `Origem_Id` INT NOT NULL,
  `Destino_Id` INT NOT NULL,
  `Aviao_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Voo_Aeroporto1_idx` (`Origem_Id` ASC) VISIBLE,
  INDEX `fk_Voo_Aeroporto2_idx` (`Destino_Id` ASC) VISIBLE,
  INDEX `fk_Voo_Aviao1_idx` (`Aviao_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Voo_Aeroporto1`
    FOREIGN KEY (`Origem_Id`)
    REFERENCES `HealthGo`.`Aeroporto` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Voo_Aeroporto2`
    FOREIGN KEY (`Destino_Id`)
    REFERENCES `HealthGo`.`Aeroporto` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Voo_Aviao1`
    FOREIGN KEY (`Aviao_Id`)
    REFERENCES `HealthGo`.`Aviao` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`Passagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`Passagem` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Preco` DECIMAL(10,2) NOT NULL,
  `Assento_Id` INT NOT NULL,
  `Voo_Id` INT NOT NULL,
  `OrdemServico_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Passagem_Assento1_idx` (`Assento_Id` ASC) VISIBLE,
  INDEX `fk_Passagem_Voo1_idx` (`Voo_Id` ASC) VISIBLE,
  INDEX `fk_Passagem_OrdemServico1_idx` (`OrdemServico_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Passagem_Assento1`
    FOREIGN KEY (`Assento_Id`)
    REFERENCES `HealthGo`.`Assento` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Passagem_Voo1`
    FOREIGN KEY (`Voo_Id`)
    REFERENCES `HealthGo`.`Voo` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Passagem_OrdemServico1`
    FOREIGN KEY (`OrdemServico_Id`)
    REFERENCES `HealthGo`.`OrdemServico` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`Imagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`Imagem` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Endereco` VARCHAR(255) NOT NULL,
  `Nome` VARCHAR(255) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`Avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`Avaliacao` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nota` INT NOT NULL,
  `Comentario` VARCHAR(255) NULL,
  `Pessoa_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Avaliacao_Pessoa1_idx` (`Pessoa_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Avaliacao_Pessoa1`
    FOREIGN KEY (`Pessoa_Id`)
    REFERENCES `HealthGo`.`Pessoa` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`Avaliacao_Servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`Avaliacao_Servico` (
  `Avaliacao_Id` INT NOT NULL,
  `PrestadorServico_Id` INT NOT NULL,
  PRIMARY KEY (`Avaliacao_Id`, `PrestadorServico_Id`),
  INDEX `fk_Avaliacao_has_PrestadorServico_PrestadorServico1_idx` (`PrestadorServico_Id` ASC) VISIBLE,
  INDEX `fk_Avaliacao_has_PrestadorServico_Avaliacao1_idx` (`Avaliacao_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Avaliacao_has_PrestadorServico_Avaliacao1`
    FOREIGN KEY (`Avaliacao_Id`)
    REFERENCES `HealthGo`.`Avaliacao` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avaliacao_has_PrestadorServico_PrestadorServico1`
    FOREIGN KEY (`PrestadorServico_Id`)
    REFERENCES `HealthGo`.`PrestadorServico` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`Hotel_Avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`Hotel_Avaliacao` (
  `Hotel_Id` INT NOT NULL,
  `Avaliacao_Id` INT NOT NULL,
  PRIMARY KEY (`Hotel_Id`, `Avaliacao_Id`),
  INDEX `fk_Hotel_has_Avaliacao_Avaliacao1_idx` (`Avaliacao_Id` ASC) VISIBLE,
  INDEX `fk_Hotel_has_Avaliacao_Hotel1_idx` (`Hotel_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Hotel_has_Avaliacao_Hotel1`
    FOREIGN KEY (`Hotel_Id`)
    REFERENCES `HealthGo`.`Hotel` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hotel_has_Avaliacao_Avaliacao1`
    FOREIGN KEY (`Avaliacao_Id`)
    REFERENCES `HealthGo`.`Avaliacao` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`Imagem_Quarto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`Imagem_Quarto` (
  `Imagem_Id` INT NOT NULL,
  `Quarto_Id` INT NOT NULL,
  PRIMARY KEY (`Imagem_Id`, `Quarto_Id`),
  INDEX `fk_Imagens_has_Quarto_Quarto1_idx` (`Quarto_Id` ASC) VISIBLE,
  INDEX `fk_Imagens_has_Quarto_Imagens1_idx` (`Imagem_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Imagens_has_Quarto_Imagens1`
    FOREIGN KEY (`Imagem_Id`)
    REFERENCES `HealthGo`.`Imagem` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Imagens_has_Quarto_Quarto1`
    FOREIGN KEY (`Quarto_Id`)
    REFERENCES `HealthGo`.`Quarto` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`Imagem_Hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`Imagem_Hotel` (
  `Imagem_Id` INT NOT NULL,
  `Hotel_Id` INT NOT NULL,
  PRIMARY KEY (`Imagem_Id`, `Hotel_Id`),
  INDEX `fk_Imagens_has_Hotel_Hotel1_idx` (`Hotel_Id` ASC) VISIBLE,
  INDEX `fk_Imagens_has_Hotel_Imagens1_idx` (`Imagem_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Imagens_has_Hotel_Imagens1`
    FOREIGN KEY (`Imagem_Id`)
    REFERENCES `HealthGo`.`Imagem` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Imagens_has_Hotel_Hotel1`
    FOREIGN KEY (`Hotel_Id`)
    REFERENCES `HealthGo`.`Hotel` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`TokenRecuperacaoSenha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`TokenRecuperacaoSenha` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Token` VARCHAR(255) NOT NULL,
  `DataExpiracao` DATETIME NOT NULL,
  `FoiUsado` TINYINT NOT NULL DEFAULT 0,
  `Pessoa_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_TokenRecuperacaoSenha_Pessoa1_idx` (`Pessoa_Id` ASC) VISIBLE,
  CONSTRAINT `fk_TokenRecuperacaoSenha_Pessoa1`
    FOREIGN KEY (`Pessoa_Id`)
    REFERENCES `HealthGo`.`Pessoa` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
