-- MySQL Script generated by MySQL Workbench
-- Mon Apr 28 15:05:29 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema HealthGo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HealthGo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HealthGo` DEFAULT CHARACTER SET utf8 ;
USE `HealthGo` ;

-- -----------------------------------------------------
-- Table `HealthGo`.`Nacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`Nacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`Estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(255) NOT NULL,
  `Sigla` CHAR(2) NULL,
  `Nacao_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Estado_Pais1_idx` (`Nacao_id` ASC) VISIBLE,
  CONSTRAINT `fk_Estado_Pais1`
    FOREIGN KEY (`Nacao_id`)
    REFERENCES `HealthGo`.`Nacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`Cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(255) NOT NULL,
  `Estado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Cidade_Estado1_idx` (`Estado_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cidade_Estado1`
    FOREIGN KEY (`Estado_id`)
    REFERENCES `HealthGo`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`Pessoa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `DataNascimento` DATE NOT NULL,
  `CPF` VARCHAR(14) NOT NULL,
  `Telefone` VARCHAR(45) NULL,
  `Email` VARCHAR(255) NOT NULL,
  `Senha` VARCHAR(255) NOT NULL,
  `EnderecoFoto` VARCHAR(255) NULL,
  `CaoGuia` TINYINT(1) NULL,
  `CEP` VARCHAR(20) NOT NULL,
  `Bairro` VARCHAR(255) NOT NULL,
  `Rua` VARCHAR(255) NOT NULL,
  `NumeroEndereco` VARCHAR(255) NOT NULL,
  `Cidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Pessoa_Cidade1_idx` (`Cidade_id` ASC) VISIBLE,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoa_Cidade1`
    FOREIGN KEY (`Cidade_id`)
    REFERENCES `HealthGo`.`Cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`Hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`Hotel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `CNPJ` VARCHAR(18) NOT NULL,
  `Nome` VARCHAR(255) NOT NULL,
  `Tipo` ENUM('Casa', 'Apartamento', 'Hostel', 'Pousada', 'Hotel') NOT NULL,
  `Email` VARCHAR(150) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  `EnderecoFoto` VARCHAR(255) NULL,
  `Site` VARCHAR(255) NULL,
  `Acessibilidade` VARCHAR(255) NULL,
  `CEP` VARCHAR(20) NOT NULL,
  `Bairro` VARCHAR(255) NOT NULL,
  `Rua` VARCHAR(255) NOT NULL,
  `NumeroEndereco` VARCHAR(255) NOT NULL,
  `Cidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Hotel_Cidade1_idx` (`Cidade_id` ASC) VISIBLE,
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  CONSTRAINT `fk_Hotel_Cidade1`
    FOREIGN KEY (`Cidade_id`)
    REFERENCES `HealthGo`.`Cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`Lembrete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`Lembrete` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NOT NULL,
  `DataInicio` DATETIME NOT NULL,
  `DataFim` DATETIME NULL,
  `Descricao` VARCHAR(255) NULL,
  `Frequencia` ENUM('NENHUMA', 'DIARIA', 'SEMANAL', 'MENSAL', 'ANUAL') NULL DEFAULT 'NENHUMA',
  `Pessoa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Lembrete_Pessoa1_idx` (`Pessoa_id` ASC) VISIBLE,
  CONSTRAINT `fk_Lembrete_Pessoa1`
    FOREIGN KEY (`Pessoa_id`)
    REFERENCES `HealthGo`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`Quarto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`Quarto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Numero` VARCHAR(25) NOT NULL,
  `Andar` INT NULL,
  `AceitaAnimal` TINYINT(1) NOT NULL,
  `Observacao` VARCHAR(255) NULL,
  `Preco` DECIMAL(10,2) NOT NULL,
  `EnderecoFoto` VARCHAR(255) NULL,
  `LimitePessoa` INT NOT NULL,
  `Hotel_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Quarto_Hotel1_idx` (`Hotel_id` ASC) VISIBLE,
  CONSTRAINT `fk_Quarto_Hotel1`
    FOREIGN KEY (`Hotel_id`)
    REFERENCES `HealthGo`.`Hotel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`OrdemServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`OrdemServico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `DataCriacao` DATETIME NOT NULL,
  `StatusOS` ENUM('Concluído', 'Em andamento', 'Cancelado') NULL,
  `Pessoa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_OrdemServico_Pessoa1_idx` (`Pessoa_id` ASC) VISIBLE,
  CONSTRAINT `fk_OrdemServico_Pessoa1`
    FOREIGN KEY (`Pessoa_id`)
    REFERENCES `HealthGo`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`OrdemServico_Hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`OrdemServico_Hotel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `StatusOS` ENUM('Concluído', 'Em andamento', 'Cancelado') NULL,
  `Preco` DECIMAL(10,2) NULL,
  `Observacao` VARCHAR(255) NULL,
  `QuantAcompanhante` INT NULL,
  `DataInicio` DATETIME NOT NULL,
  `DataFim` DATETIME NOT NULL,
  `Quarto_id` INT NOT NULL,
  `OrdemServico_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_OrdemServico_Quarto1_idx` (`Quarto_id` ASC) VISIBLE,
  INDEX `fk_OrdemServico_Hotel_OrdemServico1_idx` (`OrdemServico_id` ASC) VISIBLE,
  CONSTRAINT `fk_OrdemServico_Quarto1`
    FOREIGN KEY (`Quarto_id`)
    REFERENCES `HealthGo`.`Quarto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrdemServico_Hotel_OrdemServico1`
    FOREIGN KEY (`OrdemServico_id`)
    REFERENCES `HealthGo`.`OrdemServico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`Especialidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`Especialidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`PrestadorServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`PrestadorServico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `PrecoHora` DECIMAL(10,2) NULL,
  `Observacao` VARCHAR(255) NULL,
  `CNPJ` VARCHAR(45) NULL,
  `Especialidade_id` INT NOT NULL,
  `Pessoa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_PrestadorServico_has_Especialidade_Especialidade1_idx` (`Especialidade_id` ASC) VISIBLE,
  INDEX `fk_PrestadorServico_has_Especialidade_Pessoa1_idx` (`Pessoa_id` ASC) VISIBLE,
  CONSTRAINT `fk_PrestadorServico_has_Especialidade_Especialidade1`
    FOREIGN KEY (`Especialidade_id`)
    REFERENCES `HealthGo`.`Especialidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PrestadorServico_has_Especialidade_Pessoa1`
    FOREIGN KEY (`Pessoa_id`)
    REFERENCES `HealthGo`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`OrdemServico_PrestadorServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`OrdemServico_PrestadorServico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Preco` DECIMAL(10,2) NOT NULL,
  `HorasTrabalhadas` INT NOT NULL,
  `DataInicio` DATETIME NOT NULL,
  `DataFim` DATETIME NOT NULL,
  `StatusOS` ENUM('Concluído', 'Em andamento', 'Cancelado') NULL,
  `PrestadorServico_id` INT NOT NULL,
  `OrdemServico_id` INT NOT NULL,
  PRIMARY KEY (`id`, `OrdemServico_id`),
  INDEX `fk_OrdemServico_PrestadorServico_PrestadorServico_has_Espec_idx` (`PrestadorServico_id` ASC) VISIBLE,
  INDEX `fk_OrdemServico_PrestadorServico_OrdemServico1_idx` (`OrdemServico_id` ASC) VISIBLE,
  CONSTRAINT `fk_OrdemServico_PrestadorServico_PrestadorServico_has_Especia1`
    FOREIGN KEY (`PrestadorServico_id`)
    REFERENCES `HealthGo`.`PrestadorServico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrdemServico_PrestadorServico_OrdemServico1`
    FOREIGN KEY (`OrdemServico_id`)
    REFERENCES `HealthGo`.`OrdemServico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`Gerencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`Gerencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Ativo` TINYINT(1) NULL DEFAULT 1,
  `DataInicio` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `DataFim` DATETIME NULL,
  `Pessoa_id` INT NOT NULL,
  `Hotel_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Gerencia_Pessoa1_idx` (`Pessoa_id` ASC) VISIBLE,
  INDEX `fk_Gerencia_Hotel1_idx` (`Hotel_id` ASC) VISIBLE,
  CONSTRAINT `fk_Gerencia_Pessoa1`
    FOREIGN KEY (`Pessoa_id`)
    REFERENCES `HealthGo`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gerencia_Hotel1`
    FOREIGN KEY (`Hotel_id`)
    REFERENCES `HealthGo`.`Hotel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthGo`.`Cama_Quarto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthGo`.`Cama_Quarto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Quantidade` INT NOT NULL,
  `TipoCama` ENUM('Solteiro', 'Casal', 'Beliche', 'Futon') NOT NULL,
  `Quarto_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Quarto_id`),
  INDEX `fk_Cama_has_Quarto_Quarto1_idx` (`Quarto_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cama_has_Quarto_Quarto1`
    FOREIGN KEY (`Quarto_id`)
    REFERENCES `HealthGo`.`Quarto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
